/**
 * ANI: Abstinence Necessity Index
 * 戒断必要性指数
 *
 * 综合量表，从以下4个量表中抽取特定维度：
 * - HBI: 负面后果维度 (5题, 权重25%)
 * - PPUS: 功能损害维度 (3题, 权重30%)
 * - PPCS: 复发+戒断维度 (6题, 权重30%)
 * - R-MSGS: 性罪恶感 (19题, 权重15%)
 */

import type { QuizTemplate } from '@/types/quiz';

export const ani: QuizTemplate = {
  id: 'ani',
  title: '戒断必要性指数',
  titleEn: 'Abstinence Necessity Index (ANI)',
  description: '综合评估色情使用对生活的影响程度，科学判断是否需要开始戒断',
  category: '综合评估',
  purpose: '从负面后果、功能损害、戒断困难、心理冲突4个维度综合评估戒断必要性',
  duration: '9-11分钟',
  questionCount: 33,

  instructions: '本测评包含4个部分，请根据你的实际情况如实回答。测评结果将帮助你了解是否需要开始戒断计划。',

  questions: [
    // ========== 第一部分：负面后果 (HBI, 5题) ==========
    {
      id: 'hbi_q11',
      type: 'scale',
      question: '我的性行为干扰了我的工作或学业。',
      dimension: 'hbi_consequences',
      options: [
        { value: 5, label: '非常频繁' },
        { value: 4, label: '经常' },
        { value: 3, label: '有时' },
        { value: 2, label: '很少' },
        { value: 1, label: '从未如此' },
      ],
      required: true,
    },
    {
      id: 'hbi_q12',
      type: 'scale',
      question: '我的性行为影响了我的人际关系。',
      dimension: 'hbi_consequences',
      options: [
        { value: 5, label: '非常频繁' },
        { value: 4, label: '经常' },
        { value: 3, label: '有时' },
        { value: 2, label: '很少' },
        { value: 1, label: '从未如此' },
      ],
      required: true,
    },
    {
      id: 'hbi_q13',
      type: 'scale',
      question: '我因为性行为而忽视了重要的社交、职业或娱乐活动。',
      dimension: 'hbi_consequences',
      options: [
        { value: 5, label: '非常频繁' },
        { value: 4, label: '经常' },
        { value: 3, label: '有时' },
        { value: 2, label: '很少' },
        { value: 1, label: '从未如此' },
      ],
      required: true,
    },
    {
      id: 'hbi_q14',
      type: 'scale',
      question: '我的性行为给我带来了法律或经济问题。',
      dimension: 'hbi_consequences',
      options: [
        { value: 5, label: '非常频繁' },
        { value: 4, label: '经常' },
        { value: 3, label: '有时' },
        { value: 2, label: '很少' },
        { value: 1, label: '从未如此' },
      ],
      required: true,
    },
    {
      id: 'hbi_q15',
      type: 'scale',
      question: '即使我知道性行为会损害我的健康，我仍然继续。',
      dimension: 'hbi_consequences',
      options: [
        { value: 5, label: '非常频繁' },
        { value: 4, label: '经常' },
        { value: 3, label: '有时' },
        { value: 2, label: '很少' },
        { value: 1, label: '从未如此' },
      ],
      required: true,
    },

    // ========== 第二部分：功能损害 (PPUS, 3题) ==========
    {
      id: 'ppus_q1',
      type: 'scale',
      question: '色情使用导致我在工作或社交上出现问题。',
      dimension: 'ppus_functional',
      options: [
        { value: 5, label: '几乎总是' },
        { value: 4, label: '很频繁' },
        { value: 3, label: '经常' },
        { value: 2, label: '有时' },
        { value: 1, label: '很少' },
        { value: 0, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppus_q2',
      type: 'scale',
      question: '我因色情内容而失去了重要的关系或机会。',
      dimension: 'ppus_functional',
      options: [
        { value: 5, label: '几乎总是' },
        { value: 4, label: '很频繁' },
        { value: 3, label: '经常' },
        { value: 2, label: '有时' },
        { value: 1, label: '很少' },
        { value: 0, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppus_q3',
      type: 'scale',
      question: '我明知会造成伤害仍继续使用色情内容。',
      dimension: 'ppus_functional',
      options: [
        { value: 5, label: '几乎总是' },
        { value: 4, label: '很频繁' },
        { value: 3, label: '经常' },
        { value: 2, label: '有时' },
        { value: 1, label: '很少' },
        { value: 0, label: '从不' },
      ],
      required: true,
    },

    // ========== 第三部分：复发与戒断 (PPCS, 6题) ==========
    // 复发维度 (3题)
    {
      id: 'ppcs_q5',
      type: 'scale',
      question: '我曾尝试减少观看色情内容但未成功。',
      dimension: 'ppcs_relapse',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppcs_q11',
      type: 'scale',
      question: '当我发誓不再看色情内容时，只能坚持很短时间。',
      dimension: 'ppcs_relapse',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppcs_q17',
      type: 'scale',
      question: '我虽然抵制过，但很快又会复发。',
      dimension: 'ppcs_relapse',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },
    // 戒断维度 (3题)
    {
      id: 'ppcs_q6',
      type: 'scale',
      question: '当被阻止观看色情内容时，我会感到紧张。',
      dimension: 'ppcs_withdrawal',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppcs_q12',
      type: 'scale',
      question: '当无法观看色情内容时，我会感到烦躁。',
      dimension: 'ppcs_withdrawal',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },
    {
      id: 'ppcs_q18',
      type: 'scale',
      question: '当我一段时间没看色情内容时，我非常想念它。',
      dimension: 'ppcs_withdrawal',
      options: [
        { value: 7, label: '总是如此' },
        { value: 6, label: '很频繁' },
        { value: 5, label: '经常' },
        { value: 4, label: '有时' },
        { value: 3, label: '偶尔' },
        { value: 2, label: '很少' },
        { value: 1, label: '从不' },
      ],
      required: true,
    },

    // ========== 第四部分：性罪恶感 (R-MSGS, 19题) ==========
    {
      id: 'rmsgs_q1',
      type: 'scale',
      question: '我认为性行为应只发生在婚姻中。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q2',
      type: 'scale',
      question: '谈论性让我感到不自在。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q3',
      type: 'scale',
      question: '我对自慰感到内疚。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q4',
      type: 'scale',
      question: '我对他人的性开放态度感到震惊。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q5',
      type: 'scale',
      question: '当我想到性时，会感到羞耻。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q6',
      type: 'scale',
      question: '我认为性欲望是一种不道德的冲动。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q7',
      type: 'scale',
      question: '我担心性幻想会让我变成坏人。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q8',
      type: 'scale',
      question: '我认为享受性快感是错误的。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q9',
      type: 'scale',
      question: '我在性行为后经常感到后悔。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q10',
      type: 'scale',
      question: '我觉得性是肮脏的或令人厌恶的。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q11',
      type: 'scale',
      question: '我担心有性想法会使我显得不纯洁。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q12',
      type: 'scale',
      question: '我认为性是需要被控制和压抑的。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q13',
      type: 'scale',
      question: '我难以接受自己的性欲望。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q14',
      type: 'scale',
      question: '我认为公开讨论性话题是不恰当的。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q15',
      type: 'scale',
      question: '我因为有性欲望而感到羞愧。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q16',
      type: 'scale',
      question: '我觉得性快感与道德价值观相冲突。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q17',
      type: 'scale',
      question: '我担心性行为会让我失去他人的尊重。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q18',
      type: 'scale',
      question: '我认为表达性欲望是不恰当的。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
    {
      id: 'rmsgs_q19',
      type: 'scale',
      question: '我的宗教或文化信仰使我对性感到内疚。',
      dimension: 'rmsgs_guilt',
      options: [
        { value: 7, label: '完全同意' },
        { value: 6, label: '比较同意' },
        { value: 5, label: '有点同意' },
        { value: 4, label: '中立' },
        { value: 3, label: '有点不同意' },
        { value: 2, label: '比较不同意' },
        { value: 1, label: '完全不同意' },
      ],
      required: true,
    },
  ],

  dimensions: [
    {
      id: 'hbi_consequences',
      name: '负面后果',
      description: '性行为对工作、学业、人际关系和健康的负面影响',
      questionIds: ['hbi_q11', 'hbi_q12', 'hbi_q13', 'hbi_q14', 'hbi_q15'],
    },
    {
      id: 'ppus_functional',
      name: '功能损害',
      description: '色情使用导致的社交、工作和生活质量损害',
      questionIds: ['ppus_q1', 'ppus_q2', 'ppus_q3'],
    },
    {
      id: 'ppcs_relapse_withdrawal',
      name: '戒断困难',
      description: '尝试戒断的失败经历和无法使用时的戒断症状',
      questionIds: ['ppcs_q5', 'ppcs_q11', 'ppcs_q17', 'ppcs_q6', 'ppcs_q12', 'ppcs_q18'],
    },
    {
      id: 'rmsgs_guilt',
      name: '心理冲突',
      description: '因性行为或色情使用产生的罪恶感、羞耻感和价值观冲突',
      questionIds: [
        'rmsgs_q1', 'rmsgs_q2', 'rmsgs_q3', 'rmsgs_q4', 'rmsgs_q5',
        'rmsgs_q6', 'rmsgs_q7', 'rmsgs_q8', 'rmsgs_q9', 'rmsgs_q10',
        'rmsgs_q11', 'rmsgs_q12', 'rmsgs_q13', 'rmsgs_q14', 'rmsgs_q15',
        'rmsgs_q16', 'rmsgs_q17', 'rmsgs_q18', 'rmsgs_q19',
      ],
    },
  ],

  scoring: {
    method: 'custom', // ANI使用自定义计算方法
    scaleRange: {
      min: 0,
      max: 100,
      description: 'ANI指数范围0-100分，由4个维度加权计算得出',
    },
    ranges: [
      {
        min: 0,
        max: 25,
        level: '低戒断必要性',
        description: '你的色情使用处于低风险范围，目前没有明显的问题性使用迹象。虽然可能偶尔使用色情内容，但这并未对你的生活、工作或人际关系造成显著负面影响，也没有出现明显的失控感或戒断困难。',
        color: '#10b981', // green
        suggestions: [
          '保持健康的生活方式和多元化的娱乐活动',
          '继续关注自己的使用频率，避免形成依赖习惯',
          '培养其他健康的压力释放方式（运动、社交、兴趣爱好）',
          '如果使用频率开始增加，及时进行自我调整',
          '定期进行自我评估，保持觉察',
        ],
      },
      {
        min: 26,
        max: 50,
        level: '中等戒断必要性',
        description: '你的色情使用开始显现出一些问题倾向，可能在某些方面已经对生活产生了轻度影响。你可能经历过一些戒断尝试的失败，或在某些情况下感到一定程度的内疚和冲突。这个阶段是开始关注和调整使用习惯的重要时机。',
        color: '#f59e0b', // amber
        suggestions: [
          '建议开始有意识地限制色情内容的使用频率',
          '设定明确的使用规则和时间限制',
          '识别触发使用的情境和情绪，寻找替代应对方式',
          '考虑使用内容过滤软件或问责应用',
          '加入支持小组或在线社区获取同伴支持',
          '培养新的兴趣爱好来填补时间和精力',
          '如果问题持续或加重，建议寻求专业心理咨询',
        ],
      },
      {
        min: 51,
        max: 75,
        level: '高戒断必要性',
        description: '你的色情使用已经达到需要认真对待的程度。它可能已经对你的工作效率、人际关系、心理健康或日常功能造成了明显的负面影响。你可能多次尝试戒断但反复失败，或在无法使用时出现明显的戒断症状。你的价值观可能与使用行为产生了强烈冲突，导致显著的心理痛苦。',
        color: '#f97316', // orange
        suggestions: [
          '强烈建议寻求专业心理咨询或性治疗师的帮助',
          '制定详细的戒断计划，设定清晰的阶段性目标',
          '考虑认知行为疗法（CBT）或接纳承诺疗法（ACT）',
          '建立问责系统：向信任的朋友或治疗师汇报进度',
          '使用内容过滤和监控软件，创建安全的数字环境',
          '加入专业指导的戒断支持小组',
          '处理可能存在的共病问题（焦虑、抑郁、创伤等）',
          '改善整体生活质量：规律作息、健康饮食、定期运动',
        ],
      },
      {
        min: 76,
        max: 100,
        level: '紧急戒断必要性',
        description: '你的色情使用已经达到严重程度，可能符合临床诊断标准。它已经严重影响了你的生活质量、社会功能、人际关系或身心健康。你可能经历了严重的负面后果（如关系破裂、工作/学业问题、法律或经济困境），但仍然难以停止。戒断尝试屡次失败，戒断症状明显，价值观冲突极其强烈。这种情况需要立即采取行动，寻求专业干预。',
        color: '#ef4444', // red
        suggestions: [
          '请立即寻求专业帮助：联系精神科医生或临床心理学家',
          '可能需要密集的门诊治疗或结构化的康复计划',
          '考虑参加专业的成瘾治疗项目或住院治疗（如情况严重）',
          '全面评估心理健康状况，排查共病（ADHD、双相障碍、创伤等）',
          '考虑药物治疗配合心理治疗（如SSRIs，需医生评估）',
          '制定详细的危机干预计划，识别高风险情境',
          '告知信任的家人或朋友，建立支持网络',
          '加入专业指导的密集治疗小组或康复项目',
          '评估和治疗其他成瘾问题（酒精、药物、赌博等）',
          '彻底重建生活结构：作息、环境、社交圈、职业规划',
          '学习健康的情绪调节和压力管理技能',
          '考虑暂时改变生活环境或数字使用习惯（如断网、换手机等）',
        ],
      },
    ],
  },

  references: [
    {
      title: 'ANI指数构成',
      authors: 'ANI Research Team',
      year: 2024,
      journal: 'ANI指数综合了4个经过验证的标准化量表：HBI性欲亢进行为量表（负面后果维度）、PPUS问题性色情使用量表（功能损害维度）、PPCS问题性色情消费量表（复发与戒断维度）、R-MSGS修订版莫舍性罪恶感量表。',
    },
  ],
};
