import type { QuizTemplate } from '@/types/quiz';

/**
 * 心理年龄测试（Psychological Age Test, PAT）
 *
 * 目的：评估个体在情绪、自我认知、人际关系、责任意识、自我成长等方面的心理成熟度
 *
 * 结构：6个维度，共40道题，5点Likert量表
 * - 维度A：情绪成熟度（Emotional Maturity）- 7题
 * - 维度B：自我认知与自我接纳（Self-Awareness & Acceptance）- 6题
 * - 维度C：社会责任与人际成熟（Social Responsibility & Interpersonal Maturity）- 7题
 * - 维度D：自我控制与意志力（Self-Control & Discipline）- 6题
 * - 维度E：自我成长与目标感（Personal Growth & Purpose）- 7题
 * - 维度F：共情与亲密能力（Empathy & Intimacy）- 7题
 *
 * 理论基础：
 * - Erikson 的心理社会发展阶段理论
 * - Greenberger & Sorensen (1974) 的心理成熟度模型
 * - Bar-On (1997) 的情绪智力理论（EQ）
 * - Robitschek (1998) 的自我成长模型
 * - Kernberg (2004) 的人格整合与成熟理论
 */

export const pat: QuizTemplate = {
  id: 'pat',
  title: '心理年龄测试',
  titleEn: 'Psychological Age Test (PAT)',
  description: '评估你的心理成熟度，了解你的"心理年龄"是否与实际年龄相匹配',
  category: '心理成熟度评估',
  purpose: '评估个体在情绪、自我认知、人际关系、责任意识、自我成长等方面的心理成熟度，帮助你了解自己的"心理年龄"是否与实际年龄相匹配，是提前成熟、恰到好处，还是仍在成长中。',
  duration: '10-15分钟',
  questionCount: 40,

  instructions: '请根据你的日常行为和心理状态选择最符合的选项。1 = 完全不符合，2 = 较不符合，3 = 一般，4 = 较符合，5 = 非常符合。请尽量凭直觉回答，无需过多思考。没有"对"或"错"的答案。',

  questions: [
    // ========== 维度A：情绪成熟度（Emotional Maturity）7题 ==========
    {
      id: 'pat_1',
      type: 'scale',
      question: '我能够控制自己的情绪，而不是被情绪支配。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_2',
      type: 'scale',
      question: '当我生气时，我通常能冷静下来再行动。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_3',
      type: 'scale',
      question: '我能接受事情并不总是按我的意愿发展。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_4',
      type: 'scale',
      question: '我在冲突中更倾向于沟通，而不是发泄。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_5',
      type: 'scale',
      question: '我能够从失败中迅速调整心态。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_6',
      type: 'scale',
      question: '我很少让情绪影响到我的判断。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_7',
      type: 'scale',
      question: '面对批评时，我能够保持理智，而不是立刻防御。',
      dimension: 'emotional_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },

    // ========== 维度B：自我认知与自我接纳（Self-Awareness & Acceptance）6题 ==========
    {
      id: 'pat_8',
      type: 'scale',
      question: '我能清楚地了解自己的优点与缺点。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_9',
      type: 'scale',
      question: '我知道自己想要成为什么样的人。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_10',
      type: 'scale',
      question: '我能接纳自己的不完美。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_11',
      type: 'scale',
      question: '我会反思自己的行为并尝试改进。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_12',
      type: 'scale',
      question: '我能够承认错误并从中学习。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_13',
      type: 'scale',
      question: '我有时会花时间思考自己真正的内心需求。',
      dimension: 'self_awareness',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },

    // ========== 维度C：社会责任与人际成熟（Social Responsibility & Interpersonal Maturity）7题 ==========
    {
      id: 'pat_14',
      type: 'scale',
      question: '我在团队中能承担自己的责任。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_15',
      type: 'scale',
      question: '我会考虑他人的感受和立场。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_16',
      type: 'scale',
      question: '我能够尊重与我意见不同的人。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_17',
      type: 'scale',
      question: '我在与人相处时能保持平等与尊重。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_18',
      type: 'scale',
      question: '我理解人际关系需要相互的付出与包容。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_19',
      type: 'scale',
      question: '我能够原谅他人的错误，而不是长期记恨。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_20',
      type: 'scale',
      question: '我会为他人提供帮助，即使这对我有点不方便。',
      dimension: 'social_maturity',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },

    // ========== 维度D：自我控制与意志力（Self-Control & Discipline）6题 ==========
    {
      id: 'pat_21',
      type: 'scale',
      question: '我能够坚持完成计划好的事情。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_22',
      type: 'scale',
      question: '我能在诱惑面前保持理性。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_23',
      type: 'scale',
      question: '当事情变得困难时，我不会轻易放弃。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_24',
      type: 'scale',
      question: '我在面对压力时能保持冷静并找到解决办法。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_25',
      type: 'scale',
      question: '我不会轻易被冲动情绪支配做决定。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_26',
      type: 'scale',
      question: '我能延迟满足，为了长远目标放弃短期享乐。',
      dimension: 'self_control',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },

    // ========== 维度E：自我成长与目标感（Personal Growth & Purpose）7题 ==========
    {
      id: 'pat_27',
      type: 'scale',
      question: '我有明确的生活目标或方向。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_28',
      type: 'scale',
      question: '我相信自己的人生有意义。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_29',
      type: 'scale',
      question: '我乐于学习新的知识与技能。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_30',
      type: 'scale',
      question: '我会主动改善自己的不足。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_31',
      type: 'scale',
      question: '我能够从生活经历中看到成长的机会。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_32',
      type: 'scale',
      question: '我经常为自己设定新的目标。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_33',
      type: 'scale',
      question: '我相信自己能掌控并改变未来。',
      dimension: 'personal_growth',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },

    // ========== 维度F：共情与亲密能力（Empathy & Intimacy）7题 ==========
    {
      id: 'pat_34',
      type: 'scale',
      question: '我能理解他人的情绪，即使他们没有明说。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_35',
      type: 'scale',
      question: '当别人遇到困难时，我会真诚地关心他们。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_36',
      type: 'scale',
      question: '我能够与人建立稳定而真诚的关系。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_37',
      type: 'scale',
      question: '我在关系中能表达感受，也能倾听他人。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_38',
      type: 'scale',
      question: '我不会害怕与他人产生情感上的亲密。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_39',
      type: 'scale',
      question: '我能平衡自己的独立性与他人的需求。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
    {
      id: 'pat_40',
      type: 'scale',
      question: '我珍视人与人之间的真诚连接。',
      dimension: 'empathy',
      options: [
        { value: 1, label: '完全不符合' },
        { value: 2, label: '较不符合' },
        { value: 3, label: '一般' },
        { value: 4, label: '较符合' },
        { value: 5, label: '非常符合' },
      ],
      required: true,
    },
  ],

  dimensions: [
    {
      id: 'emotional_maturity',
      name: '情绪成熟度',
      description: '情绪控制与稳定性',
      questionIds: ['pat_1', 'pat_2', 'pat_3', 'pat_4', 'pat_5', 'pat_6', 'pat_7'],
    },
    {
      id: 'self_awareness',
      name: '自我认知与接纳',
      description: '自我理解与反思能力',
      questionIds: ['pat_8', 'pat_9', 'pat_10', 'pat_11', 'pat_12', 'pat_13'],
    },
    {
      id: 'social_maturity',
      name: '社会责任与人际成熟',
      description: '社交成熟度与共情能力',
      questionIds: ['pat_14', 'pat_15', 'pat_16', 'pat_17', 'pat_18', 'pat_19', 'pat_20'],
    },
    {
      id: 'self_control',
      name: '自我控制与意志力',
      description: '自律性与抗挫力',
      questionIds: ['pat_21', 'pat_22', 'pat_23', 'pat_24', 'pat_25', 'pat_26'],
    },
    {
      id: 'personal_growth',
      name: '自我成长与目标感',
      description: '生活方向与自我实现',
      questionIds: ['pat_27', 'pat_28', 'pat_29', 'pat_30', 'pat_31', 'pat_32', 'pat_33'],
    },
    {
      id: 'empathy',
      name: '共情与亲密能力',
      description: '情感理解与关系能力',
      questionIds: ['pat_34', 'pat_35', 'pat_36', 'pat_37', 'pat_38', 'pat_39', 'pat_40'],
    },
  ],

  scoring: {
    method: 'sum',
    scaleRange: {
      min: 40,
      max: 200,
      description: '总分范围为40-200分，得分越高表示心理成熟度越高',
    },
    ranges: [
      {
        min: 170,
        max: 200,
        level: '极高成熟度',
        description: '你心理极为成熟，能理智应对复杂情绪与人际关系。决策稳重、自省力强。心理年龄：实际年龄 +10 岁以上。',
        color: 'green',
        psychologicalTraits: '情绪稳定、自我认知清晰、责任感强、目标明确、共情能力优秀',
        suggestions: ['保持成长，但注意别过度理性、忽略感性与放松', '适当允许自己享受当下，不必总是追求完美', '在关系中保持真实，允许自己展现脆弱的一面'],
      },
      {
        min: 140,
        max: 169,
        level: '高成熟度',
        description: '你具备良好的自我控制和责任感。能在压力中保持平衡。心理年龄：实际年龄 +5 ～ 10 岁。',
        color: 'blue',
        psychologicalTraits: '情绪管理较好、有责任意识、能够自我反思、目标清晰',
        suggestions: ['适度表达情感，避免"过于懂事"而压抑自己', '在人际关系中更主动地表达需求', '平衡理性与感性，允许自己有情绪波动'],
      },
      {
        min: 110,
        max: 139,
        level: '中等成熟度',
        description: '你的心理发展与年龄相符。具备一定独立与反思力。心理年龄：实际年龄 ±3 岁。',
        color: 'yellow',
        psychologicalTraits: '情绪相对稳定、有一定自我认知、能承担基本责任',
        suggestions: ['尝试更深层地了解情绪、需求与人际连接', '培养更强的自我控制能力和延迟满足能力', '主动设定明确的人生目标并坚持执行'],
      },
      {
        min: 80,
        max: 109,
        level: '发展中阶段',
        description: '你仍在成长中，可能在自我管理或人际处理上不够稳。心理年龄：实际年龄 −5 ～ 10 岁。',
        color: 'orange',
        psychologicalTraits: '情绪波动较大、自我认知不够清晰、容易冲动、需要提升责任感',
        suggestions: ['练习情绪觉察，学习沟通与自我反思技巧', '从小事开始培养自律习惯和责任意识', '多与成熟的人交流，学习他们的处事方式', '尝试记录情绪日记，提升自我认知'],
      },
      {
        min: 40,
        max: 79,
        level: '心理发展滞后',
        description: '你可能仍处于心理依赖或回避成长阶段。心理年龄：实际年龄 −10 岁以上。',
        color: 'red',
        psychologicalTraits: '情绪控制困难、自我认知模糊、回避责任、缺乏明确目标',
        suggestions: ['从小目标开始，培养自我责任感与独立意识', '建议寻求专业心理咨询支持，系统性提升心理成熟度', '学习基本的情绪管理技巧，如深呼吸、正念练习', '多参与社交活动，提升人际交往能力'],
      },
    ],
  },

  references: [
    {
      title: 'Toward a concept of psychological maturity in adolescence',
      authors: 'Greenberger, E., & Sorensen, A.',
      journal: 'Journal of Youth and Adolescence',
      year: 1974,
      volume: '3(4)',
      pages: '329–358',
    },
    {
      title: 'Identity and the Life Cycle',
      authors: 'Erikson, E. H.',
      year: 1959,
      content: 'International Universities Press',
    },
    {
      title: 'The Emotional Quotient Inventory (EQ-i): Technical Manual',
      authors: 'Bar-On, R.',
      year: 1997,
      content: 'Multi-Health Systems',
    },
    {
      title: 'Personal growth initiative: The construct and its measure',
      authors: 'Robitschek, C.',
      journal: 'Measurement and Evaluation in Counseling and Development',
      year: 1998,
      volume: '30(4)',
      pages: '183–198',
    },
    {
      title: 'Object-Relations Theory and Clinical Psychoanalysis',
      authors: 'Kernberg, O. F.',
      year: 2004,
      content: 'Yale University Press',
    },
    {
      title: 'Emotional Intelligence: Why It Can Matter More Than IQ',
      authors: 'Goleman, D.',
      year: 1995,
      content: 'Bantam Books',
    },
  ],
};
